development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: radioco_dev
  username: postgres
  password: postgres
  pool:     5

test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: radioco_test
  username: postgres
  password: postgres
  pool:     5

production:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: radioco
  pool:     5
  

